import json
from datetime import datetime
from typing import Any, Dict

from reporting.base import ReporterBase


class BugcrowdReporter(ReporterBase):
    def render(self) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

        summary_rows = []
        for i, f in enumerate(self.findings, 1):
            sev = f.get("severity", "info").upper()
            title = f.get("title") or f.get("details", "Untitled")
            url = f.get("url", self.target)
            stage = f.get("verification_stage", "").title() or "Detected"
            confidence = f.get("confidence_score")
            cs = f"{confidence:.0f}/100" if confidence is not None else "—"
            summary_rows.append(f"| {i} | {title} | {sev} | `{url}` | {stage} | {cs} |")

        summary_table = "\n".join(summary_rows) if summary_rows else "No findings."

        per_finding = []
        for i, f in enumerate(self.findings, 1):
            title = f.get("title") or f.get("details", "Untitled")
            sev = f.get("severity", "info").upper()
            what = f.get("what_is_it") or f.get("details", "")
            impact = f.get("impact_assessment", {}).get("narrative", "")
            steps = f.get("validation_steps") or f.get("steps_to_reproduce", "")
            if isinstance(steps, list):
                steps = "\n".join(f"{j+1}. {s}" for j, s in enumerate(steps))
            remed = f.get("remediation") or f.get("recommendation", "")
            evidence = f.get("proof") or f.get("evidence", "")
            if isinstance(evidence, dict):
                evidence = json.dumps(evidence, indent=2)

            confidence = f.get("confidence_score")
            cs = f"{confidence:.0f}/100" if confidence is not None else "—"

            grouped = f.get("grouped_urls", [])
            urls = "\n".join(f"- {u}" for u in grouped) if grouped else f"- {f.get('url', self.target)}"

            per_finding.append(f"""## Finding #{i}: {title}

| Field | Value |
|-------|-------|
| Severity | {sev} |
| URL | `{f.get('url', self.target)}` |
| Verification Stage | {f.get('verification_stage', '').title() or 'Detected'} |
| Confidence | {cs} |
| CVSS | {f.get('cvss_score', '—')} ({f.get('cvss_rating', '—')}) |
| Parameter | `{f.get('parameter', '—')}` |

### Description
{what}

### Affected URLs
{urls}

### Steps to Reproduce
{steps}

### Evidence
```
{self._format_evidence(evidence, 50)}
```

### Request
```
{self._build_curl_command(f)}
```
{("### Response\n```\n" + f.get('response_excerpt', '') + "\n```\n") if f.get('response_excerpt') else ""}
{("Screenshot: " + f.get('screenshot_path', '') + "\n") if f.get('screenshot_path') else ""}
### Impact
{impact}

### Remediation
{remed}

---
""")

        body = "\n".join(per_finding) if per_finding else "No vulnerabilities detected."

        return f"""# Bugcrowd Submission: {self.target}

**Generated:** {now}
**Tool:** BugBounty-Hunter
**Total Findings:** {len(self.findings)}

## Finding Summary

| # | Title | Severity | URL | Stage | Confidence |
|---|-------|----------|-----|-------|------------|
{summary_table}

---

{body}

---

*Report generated by BugBounty-Hunter — https://github.com/anomalyco/bugbounty-hunter*
"""
