import json
from datetime import datetime
from typing import Any, Dict

from reporting.base import ReporterBase


class HackerOneReporter(ReporterBase):
    def render(self) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
        high_sev = [f for f in self.findings if f.get("severity", "info").lower() in ("critical", "high")]
        medium_sev = [f for f in self.findings if f.get("severity", "info").lower() == "medium"]
        low_sev = [f for f in self.findings if f.get("severity", "info").lower() in ("low", "info")]

        sections = []
        for label, group in [("Critical & High", high_sev), ("Medium", medium_sev), ("Low & Info", low_sev)]:
            if not group:
                continue
            sections.append(f"## {label} Severity Findings\n")
            for f in group:
                sections.append(self._vuln_section(f))

        body = "\n".join(sections) if sections else "No vulnerabilities detected during this scan."

        return f"""# Bug Bounty Report: {self.target}

**Generated:** {now}
**Tool:** BugBounty-Hunter
**Total Findings:** {len(self.findings)}

---

{body}

## Summary

This report was automatically generated by BugBounty-Hunter. \
Each finding includes CVSS score, reproduction steps, structured evidence, and impact assessment. \
Please verify each finding before submitting.

---

*Report generated by BugBounty-Hunter — https://github.com/anomalyco/bugbounty-hunter*
"""

    def _vuln_section(self, f: Any) -> str:
        sev = f.get("severity", "info").upper()
        title = f.get("title") or f.get("details", "Untitled")
        component = f.get("component") or f.get("url", self.target)
        what = f.get("what_is_it") or f.get("details", "")
        impact_narrative = self._build_impact_narrative(f)
        steps = f.get("validation_steps") or f.get("steps_to_reproduce", "")
        if isinstance(steps, list):
            steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))
        evidence = f.get("proof") or f.get("evidence") or f.get("request_response", "")
        if isinstance(evidence, dict):
            evidence = json.dumps(evidence, indent=2)
        elif isinstance(evidence, list):
            evidence_parts = []
            for i, ev in enumerate(evidence):
                if hasattr(ev, 'to_dict'):
                    ev_text = json.dumps(ev.to_dict(), indent=2)
                else:
                    ev_text = str(ev)
                desc = getattr(ev, 'description', f'Evidence #{i+1}') if hasattr(ev, 'description') else f'Evidence #{i+1}'
                evidence_parts.append(f"> **{desc}**\n```\n{ev_text}\n```")
            evidence = "\n".join(evidence_parts) if evidence_parts else ""
        remediation = f.get("remediation") or f.get("recommendation", "")
        remediation = remediation or self._build_remediation(f)

        grouped = f.get("grouped_urls", [])
        affected_urls = "\n".join(f"- {u}" for u in grouped) if grouped else f"- {f.get('url', self.target)}"

        fp_risk = f.get("false_positive_risk", "")
        parameter = f.get("parameter", "")
        curl_cmd = self._build_curl_command(f)
        response_excerpt = f.get("response_excerpt", "")
        screenshot_path = f.get("screenshot_path", "")
        verification_stage = f.get("verification_stage", "detected").title()

        screenshot_line = f"\n**Screenshot:** {screenshot_path}\n" if screenshot_path else ""

        cvss_score = self._get_cvss_score(f)
        cvss_vector = self._get_cvss_vector(f)
        cvss_rating = self._severity_rating(cvss_score)

        return f"""### {title}

**Severity:** {sev}
**CVSS:** {cvss_score:.1f} ({cvss_rating})
**CVSS Vector:** `{cvss_vector}`
**Component:** {component}
**Parameter:** {parameter or '—'}
**Verification Stage:** {verification_stage}
**False Positive Risk:** {fp_risk or '—'}

#### Summary
{what}

#### Affected URLs
{affected_urls}

#### Evidence
{evidence if evidence else "*No evidence collected.*"}

#### Request
```
{curl_cmd}
```

#### Response Excerpt
```
{self._format_evidence(response_excerpt, 50)}
```
{screenshot_line}
#### Steps to Reproduce
{steps or "1. Send a request to the affected endpoint to reproduce the vulnerability."}

#### Impact
{impact_narrative}

#### Recommended Fix
{remediation}

---
"""
