import json
from datetime import datetime
from typing import Any, Dict

from reporting.base import ReporterBase


class HackerOneReporter(ReporterBase):
    def render(self) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
        high_sev = [f for f in self.findings if f.get("severity", "info").lower() in ("critical", "high")]
        medium_sev = [f for f in self.findings if f.get("severity", "info").lower() == "medium"]
        low_sev = [f for f in self.findings if f.get("severity", "info").lower() in ("low", "info")]

        sections = []
        for label, group in [("Critical & High", high_sev), ("Medium", medium_sev), ("Low & Info", low_sev)]:
            if not group:
                continue
            sections.append(f"## {label} Severity Findings\n")
            for f in group:
                sections.append(self._vuln_section(f))

        body = "\n".join(sections) if sections else "No vulnerabilities detected during this scan."

        return f"""# Bug Bounty Report: {self.target}

**Generated:** {now}
**Tool:** BugBounty-Hunter
**Total Findings:** {len(self.findings)}

---

{body}

## Summary

This report was automatically generated by BugBounty-Hunter. \
Each finding includes severity, CVSS score, reproduction steps, evidence, and impact assessment. \
Please verify each finding before submitting.

---

*Report generated by BugBounty-Hunter — https://github.com/anomalyco/bugbounty-hunter*
"""

    def _vuln_section(self, f: Dict[str, Any]) -> str:
        sev = f.get("severity", "info").upper()
        title = f.get("title") or f.get("details", "Untitled")
        component = f.get("component") or f.get("url", self.target)
        what = f.get("what_is_it") or f.get("details", "")
        impact_narrative = f.get("impact_assessment", {}).get("narrative", "")
        steps = f.get("validation_steps") or f.get("steps_to_reproduce", "")
        if isinstance(steps, list):
            steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))
        evidence = f.get("proof") or f.get("evidence") or f.get("request_response", "")
        if isinstance(evidence, dict):
            evidence = json.dumps(evidence, indent=2)
        remediation = f.get("remediation") or f.get("recommendation", "")

        grouped = f.get("grouped_urls", [])
        affected_urls = "\n".join(f"- {u}" for u in grouped) if grouped else f"- {f.get('url', self.target)}"

        fp_risk = f.get("false_positive_risk", "")
        parameter = f.get("parameter", "")
        curl_cmd = self._build_curl_command(f)
        response_excerpt = f.get("response_excerpt", "")
        screenshot_path = f.get("screenshot_path", "")
        verification_stage = f.get("verification_stage", "detected").title()

        screenshot_line = f"**Screenshot:** {screenshot_path}\n" if screenshot_path else ""

        return f"""### {title}

**Severity:** {sev}
**Component:** {component}
**CVSS:** {f.get('cvss_score', '—')} ({f.get('cvss_rating', '—')})
**Parameter:** {parameter or '—'}
**Verification Stage:** {verification_stage}

#### Summary
{what}

#### Affected URLs
{affected_urls}

#### Steps to Reproduce
{steps}

#### Evidence
```
{self._format_evidence(evidence, 50)}
```

#### Request
```
{curl_cmd}
```

#### Response Excerpt
```
{self._format_evidence(response_excerpt, 50)}
```
{screenshot_line}
#### Impact
{impact_narrative}

#### Recommended Fix
{remediation}

#### False Positive Risk
{fp_risk}

---
"""
