"""Technology fingerprinting — identify web technologies from HTTP responses."""

import re
import threading
from typing import Any, Dict, List, Optional

from modules.utils import safe_get


TECH_SIGNATURES: Dict[str, List[Dict[str, Any]]] = {
    "framework": [
        {"name": "Django", "headers": {"x-frame-options": "DENY"}, "body": re.compile(r"django\.wsgi|csrfmiddlewaretoken|__admin_media_prefix__")},
        {"name": "Laravel", "headers": {"x-powered-by": "Laravel"}, "body": re.compile(r"laravel_session|csrf_token|Livewire|__livewire")},
        {"name": "Rails", "headers": {"x-powered-by": "Phusion|Passenger"}, "body": re.compile(r"csrf-token|rails-ujs|data-remote|data-method")},
        {"name": "Spring", "headers": {"x-application-context": ""}, "body": re.compile(r"spring|_csrf|XSRF-TOKEN")},
        {"name": "ASP.NET", "headers": {"x-aspnet-version": "", "x-powered-by": "ASP.NET"}, "body": re.compile(r"__viewstate|__eventvalidation|aspnetForm")},
        {"name": "Express", "headers": {"x-powered-by": "Express"}, "body": re.compile(r"express|connect\.sid")},
        {"name": "Flask", "headers": {}, "body": re.compile(r"flask|__debug__|secret_key")},
        {"name": "FastAPI", "headers": {}, "body": re.compile(r"fastapi|openapi\.json|docs|redoc")},
        {"name": "Next.js", "headers": {"x-powered-by": "Next.js"}, "body": re.compile(r"__NEXT_DATA__|/_next/static")},
        {"name": "Nuxt.js", "headers": {}, "body": re.compile(r"nuxt\.config|__NUXT__")},
        {"name": "Gatsby", "headers": {}, "body": re.compile(r"gatsby|___gatsby")},
    ],
    "cms": [
        {"name": "WordPress", "headers": {}, "body": re.compile(r"/wp-content/|/wp-includes/|wp-json|wordpress_[a-f0-9]{32}")},
        {"name": "Drupal", "headers": {}, "body": re.compile(r"drupal\.js|sites/default|/drupal|Drupal\.settings")},
        {"name": "Joomla", "headers": {}, "body": re.compile(r"joomla|/components/|/modules/|/templates/")},
        {"name": "Shopify", "headers": {"x-shopid": ""}, "body": re.compile(r"shopify|myshopify\.com|Shopify\.sdk")},
        {"name": "Magento", "headers": {}, "body": re.compile(r"mage\.|Magento|/static/version")},
    ],
    "language": [
        {"name": "PHP", "headers": {"x-powered-by": "PHP"}, "body": re.compile(r"php")},
        {"name": "Python", "headers": {}, "body": re.compile(r"django|flask|python|bottle|tornado")},
        {"name": "Ruby", "headers": {"x-powered-by": "Phusion|Passenger"}, "body": re.compile(r"ruby|\.erb")},
        {"name": "Java", "headers": {}, "body": re.compile(r"servlet|jsp|java|spring|tomcat")},
        {"name": "Node.js", "headers": {"x-powered-by": "Express"}, "body": re.compile(r"node|express|next\.js")},
        {"name": "Go", "headers": {}, "body": re.compile(r"go\.(min\.)?js|gorilla")},
    ],
    "proxy": [
        {"name": "Cloudflare", "headers": {"server": "cloudflare", "cf-ray": ""}, "body": re.compile(r"cloudflare|__cfduid")},
        {"name": "Akamai", "headers": {}, "body": re.compile(r"akamai|akamaized")},
        {"name": "Fastly", "headers": {"x-served-by": "", "x-cache": ""}, "body": re.compile(r"fastly")},
        {"name": "CloudFront", "headers": {"x-amz-cf-id": "", "x-amz-cf-pop": ""}, "body": re.compile(r"cloudfront")},
        {"name": "Varnish", "headers": {"x-varnish": "", "via": "varnish"}, "body": re.compile(r"varnish")},
        {"name": "Nginx", "headers": {"server": "nginx"}, "body": re.compile(r"nginx")},
        {"name": "Apache", "headers": {"server": "apache"}, "body": re.compile(r"apache")},
        {"name": "IIS", "headers": {"server": "iis", "x-powered-by": "ASP.NET"}, "body": re.compile(r"iis")},
    ],
    "waf": [
        {"name": "Cloudflare (WAF)", "headers": {"server": "cloudflare"}, "body": re.compile(r"cloudflare-nginx|attention: required|ray id:")},
        {"name": "AWS WAF", "headers": {}, "body": re.compile(r"Request blocked|waf|AWS WAF")},
        {"name": "ModSecurity", "headers": {}, "body": re.compile(r"ModSecurity|This error was generated by Mod_Security")},
        {"name": "Akamai WAF", "headers": {}, "body": re.compile(r"akamai|reference number|#ref_")},
        {"name": "F5 BIG-IP", "headers": {}, "body": re.compile(r"big-ip|F5|TS[0-9a-f]+")},
        {"name": "Sucuri", "headers": {"x-sucuri-id": ""}, "body": re.compile(r"sucuri|cloudproxy")},
    ],
    "template_engine": [
        {"name": "Jinja2", "body": re.compile(r"\{\{.*\}\}|jinja2")},
        {"name": "Twig", "body": re.compile(r"twig|\.twig")},
        {"name": "Smarty", "body": re.compile(r"smarty|\{\$.*\}")},
        {"name": "FreeMarker", "body": re.compile(r"\$\{.*\}")},
        {"name": "Velocity", "body": re.compile(r"velocity|#set\(|#if\(")},
        {"name": "Mustache", "body": re.compile(r"mustache|\{\{.*\}\}")},
        {"name": "Handlebars", "body": re.compile(r"handlebars|Handlebars\.")},
        {"name": "EJS", "body": re.compile(r"<%|%=|ejs")},
        {"name": "Pug/Jade", "body": re.compile(r"pug|jade")},
    ],
}


class TechnologyFingerprinter:
    """Identify web technologies (frameworks, CMS, languages, proxies, WAFs) from HTTP responses."""

    def __init__(self, session: Any, timeout: int):
        self.session = session
        self.timeout = timeout
        self.results: Dict[str, List[str]] = {}
        self._per_url: Dict[str, Dict[str, List[str]]] = {}
        self._lock = threading.Lock()

    def fingerprint(self, url: str) -> Dict[str, List[str]]:
        """Fingerprint a URL by analyzing response headers and body."""
        try:
            resp = safe_get(self.session, url, self.timeout)
            if not resp:
                return {}
        except Exception:
            return {}

        headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
        body = resp.text.lower()

        url_results: Dict[str, List[str]] = {}
        with self._lock:
            for category, signatures in TECH_SIGNATURES.items():
                if category not in self.results:
                    self.results[category] = []
                if category not in url_results:
                    url_results[category] = []
                for sig in signatures:
                    detected = self._match_signature(sig, headers, body)
                    if detected:
                        if sig["name"] not in self.results[category]:
                            self.results[category].append(sig["name"])
                        if sig["name"] not in url_results[category]:
                            url_results[category].append(sig["name"])
            self._per_url[url] = url_results

        return self.results

    def per_url(self) -> Dict[str, Dict[str, List[str]]]:
        return dict(self._per_url)

    def _match_signature(self, sig: Dict[str, Any], headers: Dict[str, str], body: str) -> bool:
        header_match = all(
            key in headers and (not val or val in headers[key])
            for key, val in sig.get("headers", {}).items()
        )
        body_pattern = sig.get("body")
        body_match = body_pattern.search(body) if body_pattern else False
        return header_match or bool(body_match)

    def get(self, category: str, default: Optional[List[str]] = None) -> List[str]:
        return self.results.get(category, default or [])

    def all(self) -> Dict[str, List[str]]:
        return self.results

    def summary(self) -> str:
        parts = []
        for category, items in self.results.items():
            if items:
                parts.append(f"{category}: {', '.join(items)}")
        return " | ".join(parts) if parts else "Unknown"
