"""
JWTScanner — detects JWT vulnerabilities.

Passive analysis:
  - Detect JWT tokens in Authorization headers, cookies, and response bodies
  - Decode payload and inspect claims
  - Detect weak algorithms (alg: none, alg: None)

Active testing (non-passive mode):
  - alg: none / alg: None injection
  - Weak HMAC secret brute force (common keys)
  - Algorithm confusion (RS256 public key as HS256 secret)

Lifecycle:
  DETECTED:   JWT token found in request/response
  VALIDATED:  Weak algorithm or configuration confirmed
  EXPLOITABLE: Token forged or signature bypassed
  VERIFIED:   (not applicable)

Maturity: Level 3 (Detect + Validate + typed evidence + reproduction)
"""

import base64
import json
import re
from typing import Any

from models.finding import Finding
from models.evidence import HttpRequestEvidence, ResponseExcerptEvidence
from modules.utils import (
    safe_get, finding, log, Colors, _build_curl,
    VerificationStage,
    safe_cookies_dict,
)
from scanners.base import ScannerBase, DetectionResult, ValidationResult

JWT_PATTERN = re.compile(
    r"(eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)"
)

# JWT common secrets — compiled from jwt-cracker, jwt-tool, rockyou top 1000,
# OWASP JWT cheat sheet, framework defaults, and real-world bug bounty experience.
# Includes framework defaults, common passwords, application defaults, month/day/year
# combos, and known weak secrets.
COMMON_JWT_SECRETS = [
    "secret",
    "secret_key",
    "secretkey",
    "jwt_secret",
    "jwt_secret_key",
    "jwt-secret",
    "jwt.secret",
    "jwtsecret",
    "jwt_key",
    "jwtkey",
    "jwt-token",
    "jwt.token",
    "jwt_token",
    "jwtToken",
    "token_secret",
    "token-secret",
    "token.secret",
    "token_secret_key",
    "tokenkey",
    "django-secret",
    "django_secret",
    "django.insecure",
    "django-insecure",
    "flask_secret",
    "flask-secret",
    "flask_secret_key",
    "flask.secret",
    "express_secret",
    "express-secret",
    "express-session",
    "express_secret_key",
    "spring_secret",
    "spring_secret_key",
    "springboot_secret",
    "rails_secret",
    "rails_secret_key",
    "rails-secret",
    "laravel_secret",
    "laravel-secret",
    "laravel_app_key",
    "ruby_secret",
    "ruby_secret_key",
    "devise_secret",
    "fastapi_secret",
    "fastapi-secret",
    "starlette_secret",
    "sails_secret",
    "sails.secret",
    "sails_secret_key",
    "koa_secret",
    "koa-secret",
    "koa_secret_key",
    "nextauth_secret",
    "nextauth-secret",
    "nextauth_secret_key",
    "nuxt_secret",
    "nuxt-secret",
    "nuxt_secret_key",
    "gatsby_secret",
    "gatsby-secret",
    "strapi_secret",
    "strapi-secret",
    "strapi_jwt",
    "keystone_secret",
    "keystone-secret",
    "ghost_secret",
    "ghost-secret",
    "changeme",
    "change_me",
    "change-me",
    "default",
    "default_secret",
    "default_key",
    "default_password",
    "default-pass",
    "default_pass",
    "default_secret_key",
    "defaultAppKey",
    "mysecret",
    "my_secret",
    "my-secret",
    "mysecretkey",
    "my_secret_key",
    "myapp_secret",
    "myapp-secret",
    "my_app_secret",
    "myappsecret",
    "yourownsecret",
    "your_secret",
    "your-secret",
    "your-own-secret",
    "your_own_secret",
    "your-secret-key",
    "my-jwt-secret",
    "my_jwt_secret",
    "myjwtsecret",
    "my-private-key",
    "my_private_key",
    "myprivatekey",
    "app_secret",
    "app-secret",
    "appsecret",
    "api_secret",
    "api-secret",
    "api_secret_key",
    "auth_secret",
    "auth-secret",
    "auth_secret_key",
    "session_secret",
    "session-secret",
    "session_secret_key",
    "cookie_secret",
    "cookie-secret",
    "cookie_secret_key",
    "encryption_key",
    "encryption-secret",
    "encryption_secret",
    "signing_key",
    "signing-secret",
    "signing_secret",
    "hmac_secret",
    "hmac-secret",
    "hmac_key",
    "symmetric_key",
    "symmetric-secret",
    "private_key",
    "private-key",
    "privatekey",
    "public_key",
    "public-key",
    "shared_secret",
    "shared-secret",
    "sharedsecret",
    "server_secret",
    "server-secret",
    "serversecret",
    "super_secret",
    "super-secret",
    "supersecret",
    "top_secret",
    "top-secret",
    "ultra_secret",
    "ultra-secret",
    "secret-key",
    "secret.key",
    "supersecretkey",
    "super_secret_key",
    "super-secret-key",
    "verysecret",
    "very_secret",
    "very-secret",
    "password",
    "password1",
    "password123",
    "Password",
    "PASSWORD",
    "pass",
    "pass123",
    "pass1234",
    "pass12345",
    "pass123456",
    "passw0rd",
    "p@ssword",
    "p@ssw0rd",
    "p@$$w0rd",
    "P@ssw0rd",
    "passwd",
    "Passwd",
    "Passw0rd",
    "admin",
    "admin123",
    "admin1234",
    "admin12345",
    "adminadmin",
    "administrator",
    "Admin",
    "ADMIN",
    "admin1",
    "admin12",
    "root",
    "root123",
    "root1234",
    "toor",
    "r00t",
    "R00t",
    "123456",
    "1234567",
    "12345678",
    "123456789",
    "1234567890",
    "12345",
    "1234",
    "123",
    "12345678910",
    "qwerty",
    "qwerty123",
    "qwerty12345",
    "qwertyuiop",
    "asdfgh",
    "asdfghjkl",
    "zxcvbn",
    "zxcvbnm",
    "letmein",
    "letmein123",
    "welcome",
    "welcome123",
    "welcome1",
    "login",
    "login123",
    "monkey",
    "dragon",
    "master",
    "sunshine",
    "trustno1",
    "football",
    "baseball",
    "hockey",
    "starwars",
    "iloveyou",
    "princess",
    "shadow",
    "passion",
    "batman",
    "superman",
    "harley",
    "tigger",
    "pepper",
    "ashley",
    "bailey",
    "jennifer",
    "michelle",
    "amanda",
    "andrew",
    "matthew",
    "joshua",
    "charlie",
    "thomas",
    "freedom",
    "liberty",
    "justice",
    "america",
    "eagle",
    "chocolate",
    "basketball",
    "soccer",
    "master123",
    "access",
    "access123",
    "access456",
    "hello123",
    "hello",
    "helloworld",
    "world123",
    "test",
    "test123",
    "test1234",
    "test12345",
    "testing",
    "testuser",
    "testpass",
    "test_pass",
    "test_password",
    "demo",
    "demo123",
    "sample",
    "example",
    "temporary",
    "temp123",
    "temp_pass",
    "guest",
    "guest123",
    "visitor",
    "visitor123",
    "user123",
    "user1234",
    "user12345",
    "user1",
    "company123",
    "corp123",
    "org123",
    "site123",
    "secret123",
    "secret1234",
    "key123",
    "key1234",
    "deadbeef",
    "cafebabe",
    "feedface",
    "decafc0ffee",
    "abcdef1234567890",
    "0123456789abcdef",
    "0123456789abcdef0123456789abcdef",
    "a1b2c3d4e5f6",
    "a1b2c3d4",
    "1234567890abcdef",
    "abcdef0123456789",
    "0000000000000000",
    "ffffffffffffffff",
    "aaaaaaaaaaaaaaaa",
    "bbbbbbbbbbbbbbbb",
    "0123456789",
    "9876543210",
    "aabbccdd",
    "aabbccddee",
    "0xdeadbeef",
    "0xcafebabe",
    "1234abcd",
    "abcd1234",
    "aaaabbbbccccdddd",
    "1122334455667788",
    "0123456789abcdef0123456789abcdef01234567",
    "111111",
    "1111111",
    "11111111",
    "222222",
    "333333",
    "444444",
    "555555",
    "5555555",
    "666666",
    "777777",
    "888888",
    "999999",
    "000000",
    "123321",
    "1234321",
    "123454321",
    "12345654321",
    "1234567654321",
    "1111111111",
    "2222222222",
    "3333333333",
    "100000",
    "200000",
    "300000",
    "500000",
    "1000000",
    "123456789a",
    "123456789b",
    "123456789c",
    "0000",
    "4321",
    "6969",
    "8888",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025",
    "2026",
    "20200101",
    "20210101",
    "20220101",
    "20230101",
    "20240101",
    "01012020",
    "01012021",
    "01012022",
    "01012023",
    "01012024",
    "12312020",
    "12312021",
    "12312022",
    "12312023",
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "jan",
    "feb",
    "mar",
    "apr",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
    "spring2020",
    "spring2021",
    "spring2022",
    "spring2023",
    "spring2024",
    "summer2020",
    "summer2021",
    "summer2022",
    "summer2023",
    "summer2024",
    "fall2020",
    "fall2021",
    "fall2022",
    "fall2023",
    "fall2024",
    "winter2020",
    "winter2021",
    "winter2022",
    "winter2023",
    "AKIAIOSFODNN7EXAMPLE",
    "AKIAIEXAMPLE",
    "aws_secret",
    "aws-secret",
    "aws_secret_key",
    "awssecretkey",
    "azure_secret",
    "azure_secret_key",
    "azure-key",
    "gcp_secret",
    "gcp_secret_key",
    "google_secret",
    "heroku_secret",
    "heroku-secret",
    "docker_secret",
    "docker-secret",
    "docker_secret_key",
    "kubernetes_secret",
    "k8s_secret",
    "kube_secret",
    "postgres_password",
    "postgres_secret",
    "mysql_password",
    "mysql_secret",
    "mongodb_password",
    "mongodb_secret",
    "redis_password",
    "redis_secret",
    "rabbitmq_password",
    "rabbitmq_secret",
    "kafka_secret",
    "kafka_password",
    "s3_secret",
    "s3_secret_key",
    "s3secret",
    "cloud_secret",
    "cloud_secret_key",
    "db_secret",
    "db_password",
    "dbpassword",
    "database_secret",
    "database_password",
    "jsonwebtoken",
    "json_web_token",
    "json-web-token",
    "jwt",
    "jwt!",
    "jwt123",
    "jwt@123",
    "jwt#123",
    "r2h4n6j8",
    "t3s5t7e9",
    "node_jwt_secret",
    "node-jwt-secret",
    "python_jwt_secret",
    "python-jwt-secret",
    "java_jwt_secret",
    "java-jwt-secret",
    "go_jwt_secret",
    "golang_jwt_secret",
    "php_jwt_secret",
    "php-jwt-secret",
    "dotnet_jwt_secret",
    "dotnet-jwt-secret",
    "ruby_jwt_secret",
    "ruby-jwt-secret",
    "nestjs_jwt_secret",
    "nestjs-jwt-secret",
    "socket_secret",
    "socket.io_secret",
    "socketio_secret",
    "symmetric",
    "asymmetric",
    "asymmetric_key",
    "rsa_private_key",
    "rsa-private-key",
    "rs256_private",
    "hs256_key",
    "hs384_key",
    "hs512_key",
    "hmac_sha256",
    "hmacsha256",
    "HMACSHA256",
    "SHA256",
    "sha256",
    "SHA384",
    "sha384",
    "base64_secret",
    "base64-encoded-secret",
    "base64_encoded",
    "base64encoded",
    "keystore_password",
    "keystore-password",
    "truststore_password",
    "truststore-password",
    "dev_secret",
    "dev-secret",
    "dev_secret_key",
    "development",
    "development_secret",
    "development-key",
    "staging_secret",
    "staging-secret",
    "production_secret",
    "production-secret",
    "prod_secret",
    "prod-secret",
    "prod_key",
    "local_secret",
    "local-dev",
    "local_development",
    "test_secret",
    "test-key",
    "test_secret_key",
    "ci_secret",
    "ci-secret",
    "ci_cd_secret",
    "pipeline_secret",
    "pipeline-secret",
    "actions_secret",
    "github-actions-secret",
    "env_secret",
    "env-secret",
    "environment_secret",
    "config_secret",
    "config-secret",
    "settings_secret",
    "settings-secret",
    "app_secret_key",
    "app-secret-key",
    "webhook_secret",
    "webhook-secret",
    "key",
    "keys",
    "token",
    "tokens",
    "auth",
    "authorization",
    "bearer",
    "cookie",
    "session",
    "sessions",
    "hash",
    "hashed",
    "hash_key",
    "salted",
    "encrypt",
    "encrypted",
    "decrypt",
    "cipher",
    "sign",
    "signed",
    "signature",
    "hmac",
    "hmackey",
    "sha512",
    "md5",
    "base64",
    "base64key",
    "api",
    "apikey",
    "api_key",
    "api-key",
    "cert",
    "certificate",
    "certkey",
    "ssl",
    "tls",
    "ssl_key",
    "tls_key",
    "oauth",
    "oauth2",
    "openid",
    "oidc",
    "saml",
    "saml_key",
    "cors",
    "csrf",
    "xsrf",
    "rate_limit",
    "ratelimit",
    "throttle",
    "throttling",
    "cache",
    "caching",
    "cache_key",
    "queue",
    "queue_key",
    "worker",
    "debug",
    "debug_key",
    "debugging",
    "log",
    "logging",
    "logger",
    "trace",
    "tracing",
    "trace_key",
    "monitor",
    "monitoring",
    "metrics",
    "health",
    "healthcheck",
    "health_check",
    "stats",
    "statistics",
    "s3cr3t",
    "s3cr3t_k3y",
    "s3cr3t-k3y",
    "sUp3rS3cr3t",
    "Sup3rS3cr3tK3y",
    "p@$$w0rd123",
    "p@$$w0rd!",
    "S3cr3tK3y",
    "s3cr3t_k3y_123",
    "my_$3cr3t",
    "my-s3cr3t",
    "th1s1s4s3cr3t",
    "thisisasecret",
    "thisisasupersecretkey",
    "thisisasupersecret",
    "notsosecret",
    "hardcoded_secret",
    "hardcoded-key",
    "insecure_secret",
    "insecure-key",
    "unsecure_secret",
    "unsecure-key",
    "weak_secret",
    "weak-key",
    "strong_secret",
    "strong-key",
    "random_secret",
    "random-key",
    "unique_secret",
    "unique-key",
    "complex_secret",
    "complex-key",
    "long_secret",
    "longer_secret",
    "secure_key",
    "secure_secret",
    "safe_key",
    "safe_secret",
    "hs256",
    "hs-256",
    "HS256",
    "hs384",
    "hs-384",
    "HS384",
    "hs512",
    "hs-512",
    "HS512",
    "rs256",
    "rs-256",
    "RS256",
    "rs384",
    "rs-384",
    "RS384",
    "rs512",
    "rs-512",
    "RS512",
    "es256",
    "es-256",
    "ES256",
    "es384",
    "es-384",
    "ES384",
    "es512",
    "es-512",
    "ES512",
    "ps256",
    "ps-256",
    "PS256",
    "PS384",
    "PS512",
    "abc",
    "abcd",
    "abcde",
    "abcdef",
    "abcdefg",
    "cba",
    "dcba",
    "edcba",
    "fedcba",
    "aaa",
    "aaaa",
    "aaaaa",
    "aaaaaa",
    "bbb",
    "bbbb",
    "bbbbb",
    "bbbbbb",
    "ccc",
    "cccc",
    "ccccc",
    "ddd",
    "dddd",
    "ddddd",
    "eee",
    "eeee",
    "eeeee",
    "fff",
    "ffff",
    "fffff",
    "ggg",
    "gggg",
    "hhh",
    "hhhh",
    "iii",
    "iiii",
    "jjj",
    "jjjj",
    "kkk",
    "kkkk",
    "lll",
    "llll",
    "mmm",
    "mmmm",
    "nnn",
    "nnnn",
    "ooo",
    "oooo",
    "ppp",
    "pppp",
    "qqq",
    "qqqq",
    "rrr",
    "rrrr",
    "sss",
    "ssss",
    "ttt",
    "tttt",
    "uuu",
    "uuuu",
    "vvv",
    "vvvv",
    "www",
    "wwww",
    "xxx",
    "xxxx",
    "yyy",
    "yyyy",
    "zzz",
    "zzzz",
    "love",
    "god",
    "sex",
    "money",
    "peace",
    "star",
    "moon",
    "sun",
    "sky",
    "fire",
    "water",
    "earth",
    "wind",
    "rain",
    "snow",
    "blue",
    "red",
    "green",
    "black",
    "white",
    "gold",
    "silver",
    "bronze",
    "copper",
    "iron",
    "rose",
    "lily",
    "tulip",
    "daisy",
    "lotus",
    "cat",
    "dog",
    "bird",
    "fish",
    "lion",
    "tiger",
    "bear",
    "wolf",
    "deer",
    "fox",
    "hawk",
    "crow",
    "dove",
    "swan",
    "king",
    "queen",
    "prince",
    "royal",
    "angel",
    "demon",
    "ghost",
    "spirit",
    "devil",
    "happy",
    "smile",
    "laugh",
    "joy",
    "funny",
    "beauty",
    "pretty",
    "cute",
    "lovely",
    "music",
    "song",
    "rock",
    "jazz",
    "blues",
    "light",
    "dark",
    "night",
    "day",
    "summer",
    "winter",
    "spring",
    "autumn",
    "fall",
    "ocean",
    "river",
    "lake",
    "sea",
    "wave",
    "mountain",
    "valley",
    "forest",
    "desert",
    "island",
    "truck",
    "car",
    "jeep",
    "boat",
    "plane",
    "coffee",
    "tea",
    "beer",
    "wine",
    "cocktail",
    "pizza",
    "burger",
    "steak",
    "sushi",
    "pasta",
    "apple",
    "banana",
    "cherry",
    "grape",
    "lemon",
    "world",
    "life",
    "time",
    "alex",
    "bob",
    "david",
    "edward",
    "frank",
    "george",
    "henry",
    "ivan",
    "jack",
    "kevin",
    "leo",
    "mike",
    "nick",
    "oscar",
    "paul",
    "quentin",
    "robert",
    "sam",
    "tom",
    "victor",
    "walter",
    "xavier",
    "yves",
    "zack",
    "alice",
    "betty",
    "carol",
    "diana",
    "eve",
    "fiona",
    "grace",
    "heidi",
    "iris",
    "julia",
    "kate",
    "lisa",
    "mary",
    "nancy",
    "olivia",
    "pam",
    "sarah",
    "tina",
    "uma",
    "victoria",
    "wendy",
    "xena",
    "yvonne",
    "zoe",
    "a12345",
    "a123456",
    "a1234567",
    "b12345",
    "b123456",
    "pass456",
    "pass789",
    "admin456",
    "admin789",
    "test456",
    "test789",
    "user456",
    "user789",
    "demo456",
    "abc123",
    "abc1234",
    "abc12345",
    "xyz123",
    "xyz789",
    "123abc",
    "1234abc",
    "12345abc",
    "123admin",
    "123test",
    "pass123!",
    "pass@123",
    "Pass1234",
    "Admin123!",
    "admin123!",
    "Test@123",
    "test@123",
    "User@123",
    "user@123",
    "P@ssw0rd123",
    "p@ssw0rd1234",
    "Passw0rd123",
    "passw0rd123",
    "b401b7e4c76b4b1d9c0e7a8f2c5d8e1f",
    "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6",
    "secretkey1234567890",
    "jsonwebtoken_secret",
    "my_jwt_secret_key_12345",
    "super_secret_jwt_key_2024",
    "jwt-super-secret-key-2024",
    "my-super-secret-jwt-key",
    "some-random-secret-key",
    "super-secret-key-for-jwt",
    "your-256-bit-secret",
    "your-384-bit-secret",
    "your-512-bit-secret",
    "my-256-bit-secret-key",
    "app-jwt-secret-key-2024",
    "api-jwt-secret-token",
    "very-strong-secret-key",
    "ultra-secure-jwt-secret",
    "change-me-in-production",
    "replace-me-with-real-secret",
    "set-in-environment-variable",
    "from-environment-variable",
    "env-var-secret-key",
    "dotenv-secret-key",
    "config-secret-key",
    "settings.secret_key",
    "myapp",
    "myapi",
    "myapp123",
    "myapi123",
    "appname",
    "appname_secret",
    "servicename",
    "service_secret",
    "projectname",
    "project_secret",
    "companyapp",
    "company_app_secret",
    "brandname",
    "brand_secret",
    "portal_secret",
    "dashboard_secret",
    "backend_secret",
    "frontend_secret",
    "gateway_secret",
    "proxy_secret",
    "admin_panel_secret",
    "panel_secret",
    "cms_secret",
    "blog_secret",
    "forum_secret",
    "shop_secret",
    "store_secret",
    "ecommerce_secret",
    "chat_secret",
    "messaging_secret",
    "payment_secret",
    "checkout_secret",
    "billing_secret",
    "auth_service_secret",
    "user_service_secret",
    "api_gateway_secret",
    "microservice_secret",
    "notification_secret",
    "email_secret",
    "sms_secret",
    "search_secret",
    "analytics_secret",
    "reporting_secret",
    "qwerty123456",
    "qwerty123456789",
    "asdfgh123456",
    "zxcvbn123456",
    "1q2w3e4r",
    "1q2w3e4r5t",
    "q1w2e3r4",
    "q1w2e3r4t5",
    "1qaz2wsx",
    "3edc4rfv",
    "zaq1xsw2",
    "cde3vfr4",
    "qweasd",
    "qweasdzxc",
    "123qwe",
    "123qweasd",
    "qwe123",
    "asd123",
    "zxc123",
    "1qazxsw2",
    "qazwsx123",
    "plmokn",
    "plmoknijb",
    "testtest",
    "passpass",
    "devdev",
    "qwertyuiop123",
    "Tr0ub4dor&3",
    "correcthorsebatterystaple",
    "correct-horse-battery-staple",
    "letmein12345",
    "welcome12345",
    "trustn01",
    "b@tm@n!",
    "sup3rm@n!",
    "F1ref0x!",
    "Chr0me!",
    "M0nkey!",
    "Drac0n!",
    "P@$$w0rd!",
    "p@$$w0rd123!",
    "S3cur3!",
    "s3cur3p@ss",
    "Str0ngP@ssw0rd",
    "C0mpl3x!@#",
    "S3cr3t!234",
    "jwt_secret_key_1234567890",
    "jwt_secret_key_abcdefghij",
    "super_secret_jwt_token_key",
    "json-web-token-secret-key",
    "jwt_hmac_secret_key_2024",
    "my_jwt_hmac_secret_key",
    "api_jwt_signing_secret",
    "access_token_signing_secret",
    "refresh_token_signing_secret",
    "jwt_access_token_secret",
    "jwt_refresh_token_secret",
    "signing_key_for_jwt_tokens",
    "jwt-signing-key-2024",
    "jwt-issuer-signing-key",
    "symmetric-signing-key",
    "256-bit-encryption-key",
    "128-bit-encryption-key",
    "64-bit-encryption-key",
    "encryption-key-123456",
    "signing-key-123456",
    "symmetric-key-123",
    "private-key-123456",
    "shared-secret-123456",
    "flag",
    "ctf_secret",
    "ctf-key",
    "hacker",
    "hacker123",
    "hacked",
    "exploit",
    "exploit123",
    "pentest",
    "pentest123",
    "vulnerable",
    "vuln123",
    "insecure_app",
    "broken_secret",
    "not-secure",
    "not_secure",
    "please-change-me",
    "change_me_please",
    "replace_me",
    "CHANGEME",
    "CHANGE_ME",
    "PLACEHOLDER",
    "placeholder",
    "TEMPORARY_SECRET",
    "TODO_SECRET",
    "FIXME_SECRET",
    "XXXXXXXX",
    "********",
    "____SECRET____",
    "---SECRET---",
    "examplesecret",
    "example-secret",
    "example_secret_key",
    "compose_secret",
    "docker-compose-secret",
    "docker_jwt_secret",
    "container_secret",
    "container-secret",
    "swarm_secret",
    "stack_secret",
    "compose_jwt_secret",
    "postman_secret",
    "postman-api-key",
    "postman_jwt_secret",
    "newman_secret",
    "api_key_12345",
    "api_key_test",
    "api_key_dev",
    "testing_api_key",
    "test_api_secret",
    "mock_secret",
    "fake_secret",
    "secret!",
    "secret@123",
    "secret#123",
    "SECRET",
    "Secret",
    "SeCrEt",
    "jwt123!",
    "jwt@123!",
    "jwt#123!",
    "pass@123!",
    "pass#123!",
    "admin@123!",
    "admin#123!",
    "admin!",
    "admin@123",
    "admin#123",
    "root123!",
    "root@123!",
    "test123!",
    "test@123!",
    "demo123!",
    "demo@123!",
    "changeme!",
    "changeme123",
    "default123!",
    "default@123",
    "welcome!",
    "welcome@123",
    "qwerty!",
    "qwerty@123",
    "123456!",
    "123456@123",
    "password!",
    "password@123",
    "letmein!",
    "letmein@123",
    "passw0rd!",
    "passw0rd@123",
    "p@ssw0rd!",
    "p@ssw0rd@123",
    "P@ssw0rd123!",
    "Passw0rd!",
    "Password1!",
    "password1!",
    "Root123!",
    "Test123!",
    "Demo123!",
    "Guest123!",
    "User123!",
    "Login123!",
    "00000000-0000-0000-0000-000000000000",
    "11111111-1111-1111-1111-111111111111",
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    "12345678-1234-1234-1234-123456789012",
    "abcdef01-2345-6789-abcd-ef0123456789",
    "deadbeef-dead-beef-dead-beefdeadbeef",
    "cafebabe-cafe-babe-cafe-babecafebabe",
    "0000000000000000000000000000000000000000",
    "1111111111111111111111111111111111111111",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "base64:",
    "base64:secret",
    "base64:default",
    "base64:changeme",
    "base64:password",
    "base64:jwt_secret",
    "hex:",
    "hex:secret",
    "hex:616263",
    "hex:61626364",
    "b64:",
    "b64_secret",
    "enc:",
    "encrypted:",
    "hash:",
    "hashed:",
    "jdoe",
    "asmith",
    "bjones",
    "cjohnson",
    "dwilson",
    "ebrown",
    "fdavis",
    "gmiller",
    "hwilson",
    "imoore",
    "jtaylor",
    "kanderson",
    "lthomas",
    "mjackson",
    "nmartin",
    "olee",
    "pwhite",
    "rharris",
    "sclark",
    "tlewis",
    "urobinson",
    "vwalker",
    "wyoung",
    "xallen",
    "yking",
    "zwright",
    "jane",
    "john",
    "letmein1",
    "letmein12",
    "welcome12",
    "password12",
    "test1",
    "test12",
    "demo1",
    "demo12",
    "guest1",
    "guest12",
    "root1",
    "root12",
    "secret1",
    "secret12",
    "changeme1",
    "changeme12",
    "default1",
    "default12",
    "default123",
    "access1",
    "access12",
    "master1",
    "master12",
    "pass1",
    "pass12",
    "passwd1",
    "passwd12",
    "passwd123",
    "qwerty1",
    "qwerty12",
    "abc123!",
    "abc@123",
    "abc#123",
    "abcdef1",
    "abcdef12",
    "testtest1",
    "testtest12",
    "87654321",
    "a123456789",
    "b123456789",
    "4444444444",
    "5555555555",
    "6666666666",
    "7777777777",
    "8888888888",
    "9999999999",
    "0000000000",
    "blockchain",
    "bitcoin",
    "ethereum",
    "crypto",
    "nft",
    "web3",
    "defi",
    "metaverse",
    "ai_secret",
    "ml_secret",
    "gpt_secret",
    "openai_secret",
    "openai-key",
    "chatgpt",
    "chatgpt-key",
    "algorithm",
    "random",
    "entropy",
    "aes256",
    "aes-256",
    "aes128",
    "blowfish",
    "twofish",
    "tripledes",
    "rsa_key",
    "dsa_key",
    "ecc_key",
    "keypair",
    "pubkey",
    "privkey",
    "x509",
    "ssl_cert",
    "tls_cert",
    "certificate_key",
    "secret_key_1234567890",
    "secret_key_1234567890!",
    "secret_key_1234567890@",
    "secret.key.1234567890",
    "secret-key-1234567890",
    "jwt_secret_1234567890",
    "jwt.secret.1234567890",
    "jwt-secret-1234567890",
    "jwt_key_1234567890",
    "jwt.key.1234567890",
    "jwt-key-1234567890",
    "signing_secret_1234567890",
    "signing.secret.1234567890",
    "signing-secret-1234567890",
    "hmac_secret_1234567890",
    "hmac.secret.1234567890",
    "hmac-secret-1234567890",
    "token_secret_1234567890",
    "token.secret.1234567890",
    "token-secret-1234567890",
    "api_secret_1234567890",
    "api.secret.1234567890",
    "api-secret-1234567890",
    "696969",
    "69696969",
    "iloveu",
    "iloveyou!",
    "fuckyou",
    "fuckoff",
    "biteme",
    "bitch",
    "slipknot",
    "metallica",
    "nirvana",
    "rammstein",
    "linkinpark",
    "greenday",
    "blink182",
    "sum41",
    "eminem",
    "50cent",
    "drake",
    "kanye",
    "beyonce",
    "rihanna",
    "taylor",
    "swift",
    "justin",
    "bieber",
    "selena",
    "gomez",
    "harrystyles",
    "onedirection",
    "billie",
    "eilish",
    "ariana",
    "grande",
    "ladygaga",
    "gaga",
    "madonna",
    "cher",
    "davidbowie",
    "elvis",
    "presley",
    "beatles",
    "pinkfloyd",
    "ledzeppelin",
    "acdc",
    "aerosmith",
    "bonjovi",
    "gunandroses",
    "pearljam",
    "u2",
    "radiohead",
    "coldplay",
    "oasis",
    "blur",
    "gorillaz",
    "yankees",
    "redsox",
    "cowboys",
    "packers",
    "patriots",
    "steelers",
    "lakers",
    "bulls",
    "celtics",
    "heat",
    "knicks",
    "warriors",
    "nba",
    "nfl",
    "nintendo",
    "sega",
    "playstation",
    "xbox",
    "mario",
    "zelda",
    "sonic",
    "megaman",
    "minecraft",
    "fortnite",
    "roblox",
    "amongus",
    "gta",
    "gtav",
    "reddead",
    "rdr2",
    "skyrim",
    "fallout",
    "witcher",
    "cyberpunk",
    "assassins",
    "far_cry",
    "callofduty",
    "battlefield",
    "halo",
    "destiny",
    "overwatch",
    "valorant",
    "leagueoflegends",
    "lol",
    "dota",
    "csgo",
    "counterstrike",
    "warcraft",
    "starcraft",
    "diablo",
    "worldofwarcraft",
    "wow",
    "pokemon",
    "digimon",
    "dragonball",
    "naruto",
    "onepiece",
    "bleach",
    "attackontitan",
    "demonslayer",
    "deathnote",
    "fullmetal",
    "cowboybebop",
    "evangelion",
    "ghostintheshell",
    "akira",
    "spiderman",
    "ironman",
    "batman123",
    "superman123",
    "wonderwoman",
    "flash",
    "aquaman",
    "thor",
    "hulk",
    "captainamerica",
    "blackwidow",
    "hawkeye",
    "deadpool",
    "wolverine",
    "xmen",
    "avengers",
    "guardians",
    "galaxy",
    "starwars123",
    "jedi",
    "lightsaber",
    "darthvader",
    "yoda",
    "skywalker",
    "hansolo",
    "chewbacca",
    "startrek",
    "enterprise",
    "kirk",
    "picard",
    "spock",
    "worf",
    "doctorwho",
    "tardis",
    "sherlock",
    "watson",
    "harrypotter",
    "voldemort",
    "dumbledore",
    "hagrid",
    "hermione",
    "ronweasley",
    "gandalf",
    "frodo",
    "aragorn",
    "legolas",
    "gimli",
    "sauron",
    "samwise",
    "gollum",
    "hobbit",
    "lotr",
    "gameofthrones",
    "got",
    "jon_snow",
    "khaleesi",
    "tyrion",
    "cersei",
    "arya",
    "sansa",
    "daenerys",
    "stark",
    "lannister",
    "targaryen",
    "westeros",
    "winterfell",
    "strangerthings",
    "demogorgon",
    "eleven",
    "hopper",
    "rickandmorty",
    "wubbalubbadubdub",
    "theoffice",
    "dundermifflin",
    "friends",
    "centralperk",
    "breakingbad",
    "heisenberg",
    "walterwhite",
    "jessepinkman",
    "sopranos",
    "tony",
    "thesimpsons",
    "homer",
    "familyguy",
    "petergriffin",
    "southpark",
    "kyle",
    "futurama",
    "bender",
    "bobross",
    "happylittletrees",
    "keanu",
    "reeves",
    "matrix",
    "neo",
    "morpheus",
    "trinity",
    "inception",
    "interstellar",
    "titanic",
    "avatar",
    "jurassic",
    "park",
    "backtothefuture",
    "docbrown",
    "indianajones",
    "raiders",
    "jamesbond",
    "007",
    "bond",
    "jamesbond007",
    "missionimpossible",
    "ethanhunt",
    "bourne",
    "jasonbourne",
    "terminator",
    "skynet",
    "robocop",
    "predator",
    "alien",
    "xenomorph",
    "bladerunner",
    "deckard",
    "thematrix",
    "redpill",
    "vforvendetta",
    "guyfawkes",
    "fightclub",
    "tylerdurden",
    "pulpfiction",
    "vincentvega",
    "reservoir",
    "dogs",
    "tarantino",
    "quintin",
    "iss",
    "sub",
    "aud",
    "exp",
    "nbf",
    "iat",
    "jti",
    "role",
    "roles",
    "scope",
    "scopes",
    "claim",
    "claims",
    "payload",
    "header",
    "typ",
    "typJWT",
    "cty",
    "kid",
    "jku",
    "jwk",
    "x5u",
    "x5c",
    "x5t",
    "crit",
    "b64",
    "alg",
    "enc",
    "zip",
    "sig",
    "unsigned",
    "adminadmin123",
    "admin123admin",
    "passwordpassword",
    "passpassword",
    "testtest123",
    "test123test",
    "demodemo123",
    "demo123demo",
    "devdev123",
    "dev123dev",
    "apiapikey",
    "keykeykey",
    "abcabc123",
    "xyzxyz123",
    "secretsecret",
    "secret123secret",
    "changemechangeme",
    "defaultdefault",
    "aadmin",
    "aadmin123",
    "ppassword",
    "ppassword123",
    "ttest",
    "ttest123",
    "ddev",
    "ddev123",
    "qwertyqwerty",
    "123123",
    "123123123",
    "123456123456",
    "123456789123",
    "111111111111",
    "222222222222",
    "test01",
    "test02",
    "test03",
    "admin01",
    "admin02",
    "admin03",
    "user01",
    "user02",
    "user03",
    "dev01",
    "dev02",
    "dev03",
    "prod01",
    "prod02",
    "stage01",
    "stage02",
    "jwt_secret_01",
    "jwt_secret_02",
    "secret_01",
    "secret_02",
    "key_01",
    "key_02",
    "token_01",
    "token_02",
    "api_secret_01",
    "api_secret_02",
    "owasp",
    "owasp123",
    "owasp_jwt_secret",
    "owasp-jwt-secret",
    "owasp_test_secret",
    "owasp-test-secret",
    "owasp_secret_key",
    "test_owasp_secret",
    "test-owasp-secret",
    "owasp_jwt_test",
    "owasp-jwt-test",
    "jwt_owasp_test",
    "jwt.owasp.test",
    "owasp_jwt_test_secret",
    "owasp-jwt-test-secret",
    "a",
    "aa",
    "b",
    "bb",
    "c",
    "cc",
    "d",
    "dd",
    "e",
    "ee",
    "f",
    "ff",
    "ab",
    "bc",
    "bcd",
    "bcde",
    "cd",
    "cde",
    "de",
    "def",
    "ef",
    "efg",
    "fg",
    "fgh",
    "gh",
    "ghi",
    "hi",
    "hij",
    "ij",
    "ijk",
    "jk",
    "jkl",
    "kl",
    "klm",
    "lm",
    "lmn",
    "mn",
    "mno",
    "no",
    "nop",
    "op",
    "opq",
    "pq",
    "pqr",
    "qr",
    "qrs",
    "rs",
    "rst",
    "st",
    "stu",
    "tu",
    "tuv",
    "uv",
    "uvw",
    "vw",
    "vwx",
    "wx",
    "wxy",
    "xy",
    "xyz",
    "yz",
    "x6a8v3k9m2n1p4q7r5t8u2w0y3z5",
    "a9b8c7d6e5f4g3h2i1j0k9l8m7n6",
    "m1n2b3v4c5x6z7a8s9d0f1g2h3j4",
    "k8l9m0n1b2v3c4x5z6a7s8d9f0g1",
    "p4o9i8u7y6t5r4e3w2q1",
    "z1x2c3v4b5n6m7a8s9d0f1",
    "h2j4k6l8m0n2p4q6r8s0t2",
    "g3h6j9k2l5m8n1p4q7r0s3",
    "aA1bB2cC3dD4eE5fF6gG7",
    "Aa1Bb2Cc3Dd4Ee5Ff6Gg7",
    "1a2b3c4d5e6f7g8h9i0j",
    "qWeRtYuIoPaSdFgHjKlZxCvB",
    "zAxScDfVgBhJnKmLoP",
    "1q2w3e4r5t6y7u8i9o",
    "p0o9i8u7y6t5r4e3w2q1",
    "1Q2W3E4R5T6Y7U8I9O0P",
    "aBcDeFgHiJkLmNoPqRsTuV",
    "Zxcvbnm1234567890",
    "Qwertyuiop123456789",
    "placeholder_secret",
    "placeholder-secret",
    "your-secret-here",
    "your_secret_here",
    "your-key-here",
    "your_key_here",
    "your-token-here",
    "your_token_here",
    "enter-secret-here",
    "enter_secret_here",
    "secret-goes-here",
    "secret_goes_here",
    "put-your-secret-here",
    "put_your_secret_here",
    "add-secret-here",
    "add_secret_here",
    "change-this-secret",
    "change_this_secret",
    "replace-this-secret",
    "replace_this_secret",
    "example-key-do-not-use",
    "example_key_do_not_use",
    "demo-secret-do-not-use",
    "demo_secret_do_not_use",
    "test-secret-do-not-use",
    "test_secret_do_not_use",
    "dev-secret-do-not-use",
    "dev_secret_do_not_use",
    "sample-key-not-for-prod",
    "sample_key_not_for_prod",
    "not-for-production",
    "not_for_production",
    "development-only-secret",
    "development_only_secret",
    "testing-only-secret",
    "testing_only_secret",
    "debug-only-secret",
    "debug_only_secret",
    "non-production-secret",
    "non_production_secret",
    "dont-use-in-prod",
    "dont_use_in_prod",
    "do-not-use-in-production",
    "do_not_use_in_production",
    "for-development-only",
    "for_development_only",
    "for-testing-purposes",
    "for_testing_purposes_only",
    "this-is-a-secret",
    "this-is-a-test-secret",
    "this_is_a_secret",
    "this_is_a_test_secret",
    "sample-secret-key",
    "sample_secret_key",
    "dummy-secret-key",
    "dummy_secret_key",
    "fake-secret-key",
    "fake_secret_key",
    "mock-secret-key",
    "mock_secret_key",
    "test-key-123",
    "testkey123",
    "test-key-for-jwt",
    "test_key_for_jwt",
    "dummy-key-for-testing",
    "dummy_key_for_testing",
    "fake-key-for-testing",
    "fake_key_for_testing",
    "about",
    "above",
    "abuse",
    "accept",
    "account",
    "achieve",
    "across",
    "action",
    "active",
    "actual",
    "really",
    "please",
    "always",
    "amount",
    "animal",
    "annual",
    "answer",
    "anyone",
    "anyway",
    "appeal",
    "appear",
    "around",
    "artist",
    "aspect",
    "assert",
    "assess",
    "assign",
    "assist",
    "assume",
    "attach",
    "attack",
    "attend",
    "author",
    "avenue",
    "backup",
    "became",
    "become",
    "before",
    "behalf",
    "behave",
    "behind",
    "belong",
    "beside",
    "beyond",
    "bishop",
    "bitter",
    "blamed",
    "bloody",
    "border",
    "borough",
    "bother",
    "bottle",
    "bottom",
    "bounce",
    "branch",
    "breath",
    "bridge",
    "briefly",
    "bright",
    "broken",
    "browse",
    "brutal",
    "bubble",
    "bucket",
    "budget",
    "buffer",
    "bullet",
    "bunch",
    "burden",
    "bureau",
    "button",
    "camera",
    "campus",
    "cancel",
    "carbon",
    "career",
    "castle",
    "cattle",
    "center",
    "chance",
    "change",
    "charge",
    "cheese",
    "choice",
    "choose",
    "church",
    "circle",
    "claire",
    "clause",
    "clever",
    "client",
    "clinic",
    "closed",
    "closer",
    "colony",
    "colour",
    "column",
    "combat",
    "comedy",
    "coming",
    "common",
    "comply",
    "consist",
    "consult",
    "contain",
    "content",
    "contest",
    "context",
    "control",
    "convert",
    "convince",
    "cooker",
    "corner",
    "cosmic",
    "cotton",
    "council",
    "county",
    "couple",
    "course",
    "cousin",
    "create",
    "credit",
    "crisis",
    "custom",
    "damage",
    "dance",
    "danger",
    "dealer",
    "debate",
    "decade",
    "decide",
    "defeat",
    "defend",
    "define",
    "degree",
    "demand",
    "denial",
    "depend",
    "deploy",
    "deposit",
    "derive",
    "design",
    "desire",
    "detail",
    "detect",
    "device",
    "devote",
    "differ",
    "dinner",
    "direct",
    "divide",
    "divine",
    "doctor",
    "dollar",
    "domain",
    "double",
    "drama",
    "driver",
    "during",
    "easily",
    "easter",
    "effect",
    "effort",
    "eighth",
    "either",
    "emerge",
    "empire",
    "employ",
    "enable",
    "ending",
    "energy",
    "engage",
    "engine",
    "enjoy",
    "enormous",
    "ensure",
    "entire",
    "entity",
    "equity",
    "escape",
    "estate",
    "evolve",
    "exceed",
    "except",
    "excess",
    "excuse",
    "expand",
    "expect",
    "expert",
    "explicit",
    "export",
    "expose",
    "extend",
    "extent",
    "fabric",
    "facial",
    "factor",
    "fairly",
    "family",
    "farmer",
    "father",
    "favour",
    "fellow",
    "female",
    "fibre",
    "fiction",
    "fierce",
    "fifth",
    "fifty",
    "fight",
    "figure",
    "filing",
    "filled",
    "filter",
    "final",
    "finance",
    "finger",
    "finish",
    "fiscal",
    "flight",
    "floppy",
    "flower",
    "flying",
    "follow",
    "forbid",
    "forced",
    "forget",
    "formal",
    "format",
    "former",
    "foster",
    "fourth",
    "french",
    "friend",
    "frozen",
    "future",
    "gained",
    "garden",
    "gather",
    "gender",
    "gentle",
    "gifted",
    "glance",
    "global",
    "golden",
    "govern",
    "granny",
    "grants",
    "grasp",
    "graves",
    "ground",
    "groups",
    "growth",
    "guards",
    "guess",
    "guests",
    "guides",
    "guitar",
    "handle",
    "happen",
    "harbor",
    "hardly",
    "hazard",
    "heaven",
    "height",
    "helped",
    "heroes",
    "hidden",
    "highly",
    "honest",
    "honour",
    "horror",
    "hosted",
    "hotels",
    "hunter",
    "ignore",
    "images",
    "immune",
    "impact",
    "import",
    "impose",
    "income",
    "indeed",
    "indoor",
    "infant",
    "inform",
    "injure",
    "injury",
    "inland",
    "insect",
    "insert",
    "insist",
    "insure",
    "intact",
    "intake",
    "intend",
    "intent",
    "invest",
    "invite",
    "itself",
    "jacket",
    "jockey",
    "joiner",
    "jungle",
    "junior",
    "keeper",
    "kernel",
    "killer",
    "kindly",
    "knight",
    "labour",
    "launch",
    "lawyer",
    "layout",
    "leader",
    "league",
    "lender",
    "lesson",
    "litter",
    "little",
    "living",
    "lizard",
    "loaded",
    "locate",
    "locked",
    "logical",
    "longer",
    "luxury",
    "mainly",
    "makeup",
    "manage",
    "manner",
    "marble",
    "margin",
    "marine",
    "marker",
    "market",
    "matter",
    "medium",
    "member",
    "memory",
    "mental",
    "mentor",
    "merger",
    "method",
    "middle",
    "mighty",
    "miller",
    "mining",
    "minute",
    "mirror",
    "mobile",
    "modify",
    "monster",
    "month",
    "mortal",
    "mostly",
    "mother",
    "motion",
    "murder",
    "muscle",
    "museum",
    "mutual",
    "myself",
    "namely",
    "narrow",
    "nation",
    "nature",
    "nearby",
    "nearly",
    "nicely",
    "ninety",
    "nobody",
    "normal",
    "notice",
    "notion",
    "number",
    "object",
    "obtain",
    "occupy",
    "offend",
    "office",
    "online",
    "oppose",
    "option",
    "orange",
    "orbit",
    "ordeal",
    "origin",
    "outfit",
    "outlet",
    "output",
    "palace",
    "parent",
    "parish",
    "patrol",
    "patron",
    "peanut",
    "peculiar",
    "pension",
    "people",
    "period",
    "permit",
    "person",
    "pierce",
    "pillar",
    "planet",
    "player",
    "pledge",
    "plenty",
    "pocket",
    "poetry",
    "poison",
    "police",
    "policy",
    "polish",
    "poorly",
    "postal",
    "poster",
    "potato",
    "powder",
    "prayer",
    "prefer",
    "priced",
    "prison",
    "profit",
    "proper",
    "proven",
    "public",
    "pursue",
    "puzzle",
    "racing",
    "rarely",
    "rather",
    "rating",
    "reader",
    "reason",
    "recall",
    "recent",
    "record",
    "reduce",
    "reform",
    "refuse",
    "regard",
    "regime",
    "region",
    "reject",
    "relate",
    "relief",
    "remain",
    "remedy",
    "remote",
    "remove",
    "render",
    "rental",
    "repair",
    "repeat",
    "report",
    "rescue",
    "resent",
    "resign",
    "resist",
    "resort",
    "restore",
    "retail",
    "retain",
    "retire",
    "return",
    "reveal",
    "review",
    "revolt",
    "reward",
    "rhythm",
    "riding",
    "ritual",
    "rocket",
    "ruling",
    "runner",
    "sacred",
    "safety",
    "salary",
    "saving",
    "scheme",
    "school",
    "screen",
    "script",
    "search",
    "season",
    "second",
    "sector",
    "secure",
    "select",
    "seller",
    "senior",
    "serial",
    "series",
    "settle",
    "severe",
    "shield",
    "shirt",
    "shock",
    "shoot",
    "shore",
    "short",
    "shower",
    "signal",
    "simple",
    "simply",
    "singer",
    "single",
    "sister",
    "sketch",
    "slight",
    "slowly",
    "smooth",
    "social",
    "socket",
    "sodium",
    "softly",
    "solar",
    "solely",
    "solid",
    "solved",
    "somehow",
    "sooner",
    "source",
    "speech",
    "spoken",
    "spread",
    "square",
    "stable",
    "statue",
    "status",
    "steady",
    "stolen",
    "strain",
    "strand",
    "stream",
    "street",
    "stress",
    "strict",
    "strike",
    "string",
    "stroke",
    "studio",
    "submit",
    "suburb",
    "sudden",
    "suffer",
    "summit",
    "supply",
    "surely",
    "survey",
    "switch",
    "symbol",
    "system",
    "tablet",
    "tackle",
    "talent",
    "target",
    "temple",
    "tennis",
    "terror",
    "thanks",
    "theirs",
    "theory",
    "thirty",
    "threat",
    "thrive",
    "throne",
    "thrust",
    "ticket",
    "timber",
    "tissue",
    "tongue",
    "topic",
    "torture",
    "tossed",
    "totally",
    "touch",
    "toward",
    "tracks",
    "traffic",
    "tragic",
    "trailer",
    "trainer",
    "transfer",
    "travel",
    "treaty",
    "tribal",
    "trick",
    "trophy",
    "tunnel",
    "twelve",
    "twenty",
    "twice",
    "twisted",
    "typing",
    "uganda",
    "uncle",
    "undergo",
    "unfair",
    "unfold",
    "unhappy",
    "uniform",
    "unique",
    "united",
    "unless",
    "unlike",
    "unlock",
    "unusual",
    "update",
    "useful",
    "vanish",
    "vendor",
    "versus",
    "vessel",
    "veteran",
    "viable",
    "vibrant",
    "victim",
    "videos",
    "viewer",
    "violet",
    "virgin",
    "virtue",
    "vision",
    "visits",
    "visual",
    "volume",
    "walker",
    "wander",
    "warmth",
    "weapon",
    "weekly",
    "weight",
    "welfare",
    "western",
    "window",
    "wisdom",
    "within",
    "wizard",
    "wonder",
    "wooden",
    "worthy",
    "wounded",
    "writer",
    "yellow",
    "young",
    "zombie",
    "zoning",
]

WEAK_ALG_PAYLOADS = [
    {"alg": "none", "typ": "JWT"},
    {"alg": "None", "typ": "JWT"},
    {"alg": "NONE", "typ": "JWT"},
    {"alg": "nOnE", "typ": "JWT"},
]


class JWTScanner(ScannerBase):
    SCANNER_NAME = "jwt"
    SCANNER_MATURITY = 3
    TARGET_LEVEL = True
    SCANNER_ORDER = 10

    @staticmethod
    def _decode_jwt_part(part: str) -> dict | None:
        """Decode a base64url-encoded JWT segment."""
        try:
            missing = len(part) % 4
            if missing:
                part += "=" * (4 - missing)
            padded = part.replace("-", "+").replace("_", "/")
            decoded = base64.b64decode(padded).decode("utf-8")
            return json.loads(decoded)
        except Exception:
            return None

    @staticmethod
    def _parse_jwt(token: str) -> dict | None:
        """Parse a JWT token into {header, payload, signature} or None."""
        parts = token.split(".")
        if len(parts) != 3:
            return None
        header = JWTScanner._decode_jwt_part(parts[0])
        payload = JWTScanner._decode_jwt_part(parts[1])
        if header is None or payload is None:
            return None
        return {
            "header": header,
            "payload": payload,
            "signature": parts[2],
            "raw": token,
        }

    @staticmethod
    def _forge_token(header: dict, payload: dict) -> str:
        """Forge a JWT with modified header/payload (no signature)."""
        def _b64url_encode(data: dict) -> str:
            raw = json.dumps(data, separators=(",", ":")).encode()
            return base64.urlsafe_b64encode(raw).decode().rstrip("=")

        h = _b64url_encode(header)
        p = _b64url_encode(payload)
        return f"{h}.{p}."

    @staticmethod
    def _b64url_decode(data: str) -> bytes:
        """Decode base64url with padding fix."""
        missing = len(data) % 4
        if missing:
            data += "=" * (4 - missing)
        return base64.urlsafe_b64decode(data)

    @staticmethod
    def _weak_hmac_test(token: str, secret: str) -> bool:
        """Test if a JWT was signed with a given HMAC secret.
        Uses stdlib hmac module."""
        import hmac as hmac_mod
        parts = token.split(".")
        if len(parts) != 3:
            return False
        try:
            signing_input = f"{parts[0]}.{parts[1]}".encode()
            expected_sig = hmac_mod.new(
                secret.encode(), signing_input, "sha256"
            ).digest()
            expected_b64 = base64.urlsafe_b64encode(expected_sig).decode().rstrip("=")
            return expected_b64 == parts[2]
        except Exception:
            return False

    def detect(self, url: str, parameter: str | None = None) -> list[DetectionResult]:
        results: list[DetectionResult] = []
        resp = safe_get(self.session, url, self.timeout)
        if not resp:
            return results

        jwts_found: list[dict] = []

        # Check Authorization header
        auth = resp.request.headers.get("Authorization", "") if hasattr(resp, "request") else ""
        if auth.lower().startswith("bearer "):
            token = auth[7:]
            parsed = self._parse_jwt(token)
            if parsed:
                jwts_found.append(parsed)
                results.append(DetectionResult(
                    url=url, parameter="Authorization",
                    payload=token[:80],
                    context="jwt_in_auth_header",
                    raw_response=resp,
                    evidence_signals=["JWT found in Authorization: Bearer header"],
                ))

        # Check Set-Cookie
        set_cookie = resp.headers.get("Set-Cookie", "")
        if set_cookie:
            match = JWT_PATTERN.search(set_cookie)
            if match:
                token = match.group(1)
                parsed = self._parse_jwt(token)
                if parsed:
                    jwts_found.append(parsed)
                    results.append(DetectionResult(
                        url=url, parameter="Set-Cookie",
                        payload=token[:80],
                        context="jwt_in_cookie",
                        raw_response=resp,
                        evidence_signals=["JWT found in Set-Cookie header"],
                    ))

        # Check response body
        if resp.text:
            for match in JWT_PATTERN.finditer(resp.text):
                token = match.group(1)
                parsed = self._parse_jwt(token)
                if parsed:
                    jwts_found.append(parsed)
                    results.append(DetectionResult(
                        url=url, parameter="response_body",
                        payload=token[:80],
                        context="jwt_in_response_body",
                        raw_response=resp,
                        evidence_signals=["JWT found in response body"],
                    ))
                    break  # One per response is enough

        # Analyze each found JWT for weak alg
        for parsed in jwts_found:
            alg = parsed["header"].get("alg", "").lower()
            if alg == "none":
                results.append(DetectionResult(
                    url=url, parameter="alg",
                    payload=parsed["header"].get("alg", ""),
                    context="jwt_alg_none",
                    raw_response=resp,
                    evidence_signals=[f"JWT uses alg=none (no signature)"],
                ))

        return results

    def validate(self, url: str, detection: DetectionResult | None = None) -> list[dict]:
        """Attempt to exploit JWT weaknesses.
        Forged tokens are sent to the target URL to test acceptance."""
        if self.config.get("passive") or self.config.get("dry_run"):
            return []  # Skip active testing in passive mode

        results: list[dict] = []
        resp = safe_get(self.session, url, self.timeout)
        if not resp:
            return results

        # Collect JWTs from response
        all_jwts: list[dict] = []

        # Check Auth header
        auth = resp.request.headers.get("Authorization", "") if hasattr(resp, "request") else ""
        if auth.lower().startswith("bearer "):
            parsed = self._parse_jwt(auth[7:])
            if parsed:
                all_jwts.append(parsed)

        # Check Set-Cookie
        set_cookie = resp.headers.get("Set-Cookie", "")
        if set_cookie:
            match = JWT_PATTERN.search(set_cookie)
            if match:
                parsed = self._parse_jwt(match.group(1))
                if parsed:
                    all_jwts.append(parsed)

        # Check response body
        if resp.text:
            for match in JWT_PATTERN.finditer(resp.text):
                parsed = self._parse_jwt(match.group(1))
                if parsed:
                    all_jwts.append(parsed)
                    break

        for parsed in all_jwts:
            orig_token = parsed["raw"]

            # Test alg=none
            for weak_header in WEAK_ALG_PAYLOADS:
                forged = self._forge_token(weak_header, parsed["payload"])
                test_resp = safe_get(
                    self.session, url, self.timeout,
                    headers={"Authorization": f"Bearer {forged}"} if auth else {},
                    raise_for_status=False,
                )
                if test_resp and test_resp.status_code == 200:
                    results.append({
                        "confirmed": True,
                        "method": "alg_none",
                        "url": url,
                        "detail": f"JWT with alg={weak_header['alg']} accepted by server",
                        "forged_token": forged[:80],
                    })
                    break

            # Test weak HMAC secrets
            for secret in COMMON_JWT_SECRETS:
                if self._weak_hmac_test(orig_token, secret):
                    forged = self._forge_token(
                        parsed["header"],
                        {**parsed["payload"], "iat": 1234567890},
                    )
                    results.append({
                        "confirmed": True,
                        "method": "weak_hmac_secret",
                        "url": url,
                        "detail": f"JWT HMAC secret cracked: '{secret}'",
                        "forged_token": forged[:80],
                    })
                    break

        return results

    def generate_reproduction(self, f: dict) -> list[str]:
        url = f["url"]
        vuln_type = f.get("vuln_type", "")
        if vuln_type == "JWT: alg=none":
            return [
                f"Capture the JWT from {url}",
                f"The JWT header contains alg=none — no signature is required",
                "Send a modified JWT with any payload and alg=none, no signature",
                "Observe that the server accepts the forged token",
            ]
        if vuln_type == "JWT Token Disclosure":
            return [
                f"Send request to {url}",
                f"Observe the response contains a JWT token",
                "Decode the JWT payload to inspect claims",
            ]
        return [
            f"Send request to {url} and locate JWT tokens",
            "Inspect JWT header and payload for weak configurations",
        ]

    def scan(self, target_urls: list[str] | None = None) -> list[Finding]:
        self._prepare_scan()
        target = self.config.get("target", "")
        if not target or not self._in_scope(target):
            return []

        urls_to_check = [target]
        for sub in (self.recon.get("subdomains", []) or [])[:20]:
            sub_url = f"https://{sub}"
            if self._in_scope(sub_url):
                urls_to_check.append(sub_url)

        for url in urls_to_check:
            detections = self.detect(url)
            if not detections:
                continue

            validations = self.validate(url)

            for d in detections:
                curl_cmd = _build_curl("GET", url, dict(self.session.headers), cookies=safe_cookies_dict(self.session.cookies))
                resp = d.raw_response
                resp_text = resp.text[:500] if resp else ""

                matched_v = [v for v in validations if v["confirmed"]]

                if d.context == "jwt_alg_none":
                    vuln_type = "JWT: alg=none"
                    severity = "critical"
                    details = "JWT token uses alg=none — signature verification is disabled"
                    ev = f"JWT alg=none in header"
                    stage = VerificationStage.EXPLOITABLE.value if matched_v else VerificationStage.DETECTED.value
                elif matched_v:
                    vuln_type = f"JWT Weakness: {matched_v[0]['method']}"
                    severity = "critical"
                    details = matched_v[0]["detail"]
                    ev = f"JWT weakness: {matched_v[0]['method']}"
                    stage = VerificationStage.VALIDATED.value
                else:
                    vuln_type = "JWT Token Disclosure"
                    severity = "medium"
                    details = "JWT token found in response — may contain sensitive claims"
                    ev = f"JWT token prefix: {d.payload[:50]}"
                    stage = VerificationStage.DETECTED.value

                # Decode payload for details
                parsed = self._parse_jwt(d.payload)
                if parsed and parsed["payload"]:
                    claims = parsed["payload"]
                    sensitive_claims = [k for k in claims if k in ("sub", "role", "groups", "admin", "iat", "exp", "nbf", "jti")]
                    if sensitive_claims:
                        details += f" — claims: {', '.join(sensitive_claims)}"

                f = finding(
                    vuln_type=vuln_type,
                    url=url,
                    severity=severity,
                    details=details,
                    evidence=ev,
                    request=curl_cmd,
                    response_excerpt=resp_text,
                    steps_to_reproduce=self.generate_reproduction({"url": url, "vuln_type": vuln_type}),
                    verification_stage=stage,
                )
                if f:
                    self._enrich_finding(f, 0, f["verification_stage"])
                    fp = f.get("fingerprint", "")
                    if fp:
                        req_ev = HttpRequestEvidence(
                            method="GET",
                            url=url,
                            curl_command=curl_cmd,
                        )
                        self.evidence_engine.store(req_ev)
                        self.evidence_engine.link_to_finding(req_ev, fp)
                    self._add_finding(f)
                    log(f"  [JWT] {url} — {vuln_type}", Colors.YELLOW, verbose_only=True, verbose=self.verbose)

        return self._get_findings()
